### ISSUE TITLE
How do I follow a user's posts?

### ISSUE THREAD

**Issue by BloomAutist47** [SpiderStrategies/node-tweet-stream#60]
`t.follow()`

I assume its this function but i'm just too confused how to use it

**Comment by cmbuckley** [comment]
The `follow()` filter uses Twitter user IDs, not usernames. So you need to use something like https://tweeterid.com/ to get the ID, and follow that instead of the username.

Twitter docs (no examples so easy to miss this detail): https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/guides/basic-stream-parameters#follow

**Comment by BloomAutist47** [comment]
forgot to reply. Thanks a lot!
